Final Summer 2023 Release Updates
medallia/public-api-swaggers pull request #15
Opened 2023-05-31 15:49 UTC by jpmanavalan

2023-08-22 19:46 UTC, cverges-medallia requested changes

2023-08-22 19:46 UTC, cverges-medallia commented on inbound.yaml
> +              description: Displays the available method to interact with that API path. Typically will be post
Last sentence here kinda trails off.

2023-08-22 19:46 UTC, cverges-medallia commented on inbound.yaml
> +        Cloud 2023 Fall Release as a generally available beta feature.
nit: Wrap to 80 chars and put on a separate line:
```
description:
  Inspect an importer...
```

2023-08-27 16:37 UTC, jpmanavalan commented
@cverges-medallia Updated based on your comments

2023-08-30 23:26 UTC, cverges-medallia approved these changes

2023-08-30 23:26 UTC, merged